services:
  codefever:
    image: zheng/codefever-community-lite:latest
    container_name: codefever
    ports:
      - "82:80"
      #- "22:22"
    depends_on:
      - codefever-mysql
    volumes:
      - /data/codefever/git-storage:/data/www/codefever-community/git-storage
      - /data/codefever/logs:/data/www/codefever-community/application/logs
    environment:
      DB_HOST: codefever-mysql
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASS: "1234" # Need to be the same as MYSQL_ROOT_PASSWORD
      DB_NAME: "codefever_community"

  codefever-mysql:
    image: mysql:5.7.31
    container_name: codefever-mysql
    privileged: true
    volumes:
      - /data/codefever/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
        '--max_connections=3000'
    ]
